-- ==============================================================================
-- CCE Matcher Service — let history ids be allocated 50 at a time
-- ==============================================================================
-- Flyway Migration: V6
-- Database: PostgreSQL 16
--
-- step_instance_history and protocol_instance_history took their ids from the BIGSERIAL default, which
-- the entities mapped as IDENTITY. IDENTITY makes Hibernate run every INSERT the moment it is persisted,
-- to read the generated key back, so history rows could never be sent as a JDBC batch — the Step SLA
-- Service writes one per verdict, up to a hundred per transaction, and each was its own round trip.
--
-- The entities (cce-common-util) now draw from the same sequences through Hibernate's pooled optimizer
-- with an allocation size of 50: one nextval hands a service instance the 50 ids ending at the value
-- returned, and the inserts queue until flush. For that to be sound the sequence itself must step by 50,
-- which is what this migration does. Hibernate checks the two agree at startup and refuses to start if
-- they do not, so this migration must run before any service on the new cce-common-util starts —
-- deploy Matcher first, as for every schema change.
--
-- Safe alongside anything still using the column default: a plain nextval returns v and uses v, which
-- lies inside the block (v-49 .. v] that nobody else was handed. Ids stop being in insert order across
-- writers, but nothing orders history by id — reconstruction orders by changed_at, and ClickHouse uses
-- the id only as the row's unique key.
--
-- The sequence is found through pg_get_serial_sequence rather than assumed, because a database upgraded
-- from 1.x did not get these tables from V1. Whatever it is called, it ends up named
-- <table>_id_seq (the name the entities map), stepping by 50; an identity column is also relaxed to
-- BY DEFAULT, since GENERATED ALWAYS would reject the ids Hibernate now supplies.

DO $$
DECLARE
    history_table   TEXT;
    found_sequence  TEXT;
    wanted_sequence TEXT;
    identity_kind   "char";
BEGIN
    FOREACH history_table IN ARRAY ARRAY['step_instance_history', 'protocol_instance_history'] LOOP
        wanted_sequence := history_table || '_id_seq';
        found_sequence := pg_get_serial_sequence('public.' || history_table, 'id');

        IF found_sequence IS NULL THEN
            RAISE EXCEPTION '%.id is backed by no sequence — cannot allocate ids by block', history_table;
        END IF;

        IF found_sequence <> 'public.' || wanted_sequence THEN
            EXECUTE format('ALTER SEQUENCE %s RENAME TO %I', found_sequence, wanted_sequence);
        END IF;

        SELECT a.attidentity INTO identity_kind
        FROM pg_attribute a
        WHERE a.attrelid = ('public.' || history_table)::regclass AND a.attname = 'id';

        IF identity_kind = 'a' THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', history_table);
        END IF;

        IF identity_kind IN ('a', 'd') THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET INCREMENT BY 50', history_table);
        ELSE
            EXECUTE format('ALTER SEQUENCE %I INCREMENT BY 50', wanted_sequence);
        END IF;
    END LOOP;
END $$;
